apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_demo
spec:
  selector:
    matchLabels:
      app: nginx_demo
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx_demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
